### ISSUE TITLE
MongoDB or SQL?

### ISSUE THREAD

**Issue by faraazahmad** [startup-hub-sih/backend#8]
Should we use MongoDB (MongooseJS) or PostgreSQL (SQL) for the project?

#### Following are some comparisons

https://blog.panoply.io/postgresql-vs-mongodb
https://www.mongodb.com/compare/mongodb-postgresql
https://bytescout.com/blog/mongodb-vs-postgresql.html

**Comment by faraazahmad** [comment]
MongoDB seems more suitable to me

**Comment by junedraghib** [comment]
that seems suitable to mee too

**Comment by faraazahmad** [comment]
mongo it is then
